/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsItWorkflowsRouteImport } from './routes/ops/it/workflows'
import { Route as OpsItDeployRouteImport } from './routes/ops/it/deploy'
import { Route as OpsItDashboardRouteImport } from './routes/ops/it/dashboard'
import { Route as OpsItChecksRouteImport } from './routes/ops/it/checks'
import { Route as OpsItBatchRouteImport } from './routes/ops/it/batch'
import { Route as OpsDrRunbooksRouteImport } from './routes/ops/dr/runbooks'
import { Route as OpsDrOverviewRouteImport } from './routes/ops/dr/overview'
import { Route as OpsDrDrillsRouteImport } from './routes/ops/dr/drills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsItWorkflowsRoute = OpsItWorkflowsRouteImport.update({
  id: '/ops/it/workflows',
  path: '/ops/it/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsItDeployRoute = OpsItDeployRouteImport.update({
  id: '/ops/it/deploy',
  path: '/ops/it/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsItDashboardRoute = OpsItDashboardRouteImport.update({
  id: '/ops/it/dashboard',
  path: '/ops/it/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsItChecksRoute = OpsItChecksRouteImport.update({
  id: '/ops/it/checks',
  path: '/ops/it/checks',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsItBatchRoute = OpsItBatchRouteImport.update({
  id: '/ops/it/batch',
  path: '/ops/it/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsDrRunbooksRoute = OpsDrRunbooksRouteImport.update({
  id: '/ops/dr/runbooks',
  path: '/ops/dr/runbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsDrOverviewRoute = OpsDrOverviewRouteImport.update({
  id: '/ops/dr/overview',
  path: '/ops/dr/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsDrDrillsRoute = OpsDrDrillsRouteImport.update({
  id: '/ops/dr/drills',
  path: '/ops/dr/drills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ops/dr/drills': typeof OpsDrDrillsRoute
  '/ops/dr/overview': typeof OpsDrOverviewRoute
  '/ops/dr/runbooks': typeof OpsDrRunbooksRoute
  '/ops/it/batch': typeof OpsItBatchRoute
  '/ops/it/checks': typeof OpsItChecksRoute
  '/ops/it/dashboard': typeof OpsItDashboardRoute
  '/ops/it/deploy': typeof OpsItDeployRoute
  '/ops/it/workflows': typeof OpsItWorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ops/dr/drills': typeof OpsDrDrillsRoute
  '/ops/dr/overview': typeof OpsDrOverviewRoute
  '/ops/dr/runbooks': typeof OpsDrRunbooksRoute
  '/ops/it/batch': typeof OpsItBatchRoute
  '/ops/it/checks': typeof OpsItChecksRoute
  '/ops/it/dashboard': typeof OpsItDashboardRoute
  '/ops/it/deploy': typeof OpsItDeployRoute
  '/ops/it/workflows': typeof OpsItWorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ops/dr/drills': typeof OpsDrDrillsRoute
  '/ops/dr/overview': typeof OpsDrOverviewRoute
  '/ops/dr/runbooks': typeof OpsDrRunbooksRoute
  '/ops/it/batch': typeof OpsItBatchRoute
  '/ops/it/checks': typeof OpsItChecksRoute
  '/ops/it/dashboard': typeof OpsItDashboardRoute
  '/ops/it/deploy': typeof OpsItDeployRoute
  '/ops/it/workflows': typeof OpsItWorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ops/dr/drills'
    | '/ops/dr/overview'
    | '/ops/dr/runbooks'
    | '/ops/it/batch'
    | '/ops/it/checks'
    | '/ops/it/dashboard'
    | '/ops/it/deploy'
    | '/ops/it/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ops/dr/drills'
    | '/ops/dr/overview'
    | '/ops/dr/runbooks'
    | '/ops/it/batch'
    | '/ops/it/checks'
    | '/ops/it/dashboard'
    | '/ops/it/deploy'
    | '/ops/it/workflows'
  id:
    | '__root__'
    | '/'
    | '/ops/dr/drills'
    | '/ops/dr/overview'
    | '/ops/dr/runbooks'
    | '/ops/it/batch'
    | '/ops/it/checks'
    | '/ops/it/dashboard'
    | '/ops/it/deploy'
    | '/ops/it/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsDrDrillsRoute: typeof OpsDrDrillsRoute
  OpsDrOverviewRoute: typeof OpsDrOverviewRoute
  OpsDrRunbooksRoute: typeof OpsDrRunbooksRoute
  OpsItBatchRoute: typeof OpsItBatchRoute
  OpsItChecksRoute: typeof OpsItChecksRoute
  OpsItDashboardRoute: typeof OpsItDashboardRoute
  OpsItDeployRoute: typeof OpsItDeployRoute
  OpsItWorkflowsRoute: typeof OpsItWorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/it/workflows': {
      id: '/ops/it/workflows'
      path: '/ops/it/workflows'
      fullPath: '/ops/it/workflows'
      preLoaderRoute: typeof OpsItWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/it/deploy': {
      id: '/ops/it/deploy'
      path: '/ops/it/deploy'
      fullPath: '/ops/it/deploy'
      preLoaderRoute: typeof OpsItDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/it/dashboard': {
      id: '/ops/it/dashboard'
      path: '/ops/it/dashboard'
      fullPath: '/ops/it/dashboard'
      preLoaderRoute: typeof OpsItDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/it/checks': {
      id: '/ops/it/checks'
      path: '/ops/it/checks'
      fullPath: '/ops/it/checks'
      preLoaderRoute: typeof OpsItChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/it/batch': {
      id: '/ops/it/batch'
      path: '/ops/it/batch'
      fullPath: '/ops/it/batch'
      preLoaderRoute: typeof OpsItBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/dr/runbooks': {
      id: '/ops/dr/runbooks'
      path: '/ops/dr/runbooks'
      fullPath: '/ops/dr/runbooks'
      preLoaderRoute: typeof OpsDrRunbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/dr/overview': {
      id: '/ops/dr/overview'
      path: '/ops/dr/overview'
      fullPath: '/ops/dr/overview'
      preLoaderRoute: typeof OpsDrOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/dr/drills': {
      id: '/ops/dr/drills'
      path: '/ops/dr/drills'
      fullPath: '/ops/dr/drills'
      preLoaderRoute: typeof OpsDrDrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsDrDrillsRoute: OpsDrDrillsRoute,
  OpsDrOverviewRoute: OpsDrOverviewRoute,
  OpsDrRunbooksRoute: OpsDrRunbooksRoute,
  OpsItBatchRoute: OpsItBatchRoute,
  OpsItChecksRoute: OpsItChecksRoute,
  OpsItDashboardRoute: OpsItDashboardRoute,
  OpsItDeployRoute: OpsItDeployRoute,
  OpsItWorkflowsRoute: OpsItWorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
